[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.128.0",
    "grandalf>=0.8",
    "keract>=4.5.2",
    "networkx>=3.4.2",
    "nptyping>=2.5.0",
    "pillow>=12.1.0",
    "pyclustering>=0.10.1.2",
    "redis>=7.1.0",
    "scikit-learn>=1.7.2",
    "tensorflow[and-cuda]>=2.18.1",
    "tensorflow-datasets>=4.9.9",
    "tqdm>=4.67.1",
    "umap-learn>=0.5.9.post2",
    "uvicorn>=0.40.0",
    "pydot>=4.0.1",
]
